spring:
  r2dbc:
    url: r2dbc:postgresql://${POSTGRESQL_ADDON_HOST:localhost}:${POSTGRESQL_ADDON_PORT:5432}/${POSTGRESQL_ADDON_DB:escape-camp}
    username: ${POSTGRESQL_ADDON_USER:admin}
    password: ${POSTGRESQL_ADDON_PASSWORD:guess-what}
    pool:
      initialSize: 2
      maxSize: 10
    properties:
      sslMode: ${POSTGRESQL_R2DBC_SSL_MODE:DISABLE}
  liquibase:
    change-log: classpath:db/changelog/db-changelog.sql
    url: jdbc:postgresql://${POSTGRESQL_ADDON_HOST:localhost}:${POSTGRESQL_ADDON_PORT:5432}/${POSTGRESQL_ADDON_DB:escape-camp}
    user: ${POSTGRESQL_ADDON_USER:admin}
    password: ${POSTGRESQL_ADDON_PASSWORD:guess-what}

organizer:
  password: ${ORGANIZER_PASSWORD:"7P2byKz39G!FGY"}

jwt:
  accessTokenExpiration: ${ACCESS_TOKEN_EXPIRATION:PT3H}
  issuer: ${JWT_ISSUER:https://escamp-camp.elgregos.me}
  secretKey: ${JWT_SECRET_KEY:youllneverguesswhatismysecretbutyoucantry}

game:
  riddles:
    - riddle-1:
        solution: ${RIDDLE_1_SOLUTION}
    - riddle-2:
        solution: ${RIDDLE_2_SOLUTION}
    - riddle-3:
        solution: ${RIDDLE_3_SOLUTION}
    - riddle-4:
        solution: ${RIDDLE_4_SOLUTION}
  sseHeartbeatPeriod: ${SSE_HEARTBEAT_PERIOD:PT20S}
  maxDuration: ${GAME_MAX_DURATION:PT90M}

logging:
  level:
    org:
      springframework:
        r2dbc: INFO
    io:
      r2dbc:
        postgresql:
          QUERY: INFO
          PARAM: INFO
