name: Release Escape Camp

on:
  milestone:
    types: [ closed ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Release
        uses: gradle/gradle-build-action@v2
        with:
          arguments: release -Prelease.forceVersion=${{ github.event.milestone.title }} -Prelease.customPassword=${GITHUB_TOKEN} -Prelease.customUsername=${GITHUB_ACTOR}
          build-root-directory: backend
      - name: Merge in production
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: 'main'
          target_branch: 'production'
          github_token: ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
