name: Escape Camp Backend CI

on:
  push:
    branches-ignore:
      - 'production'
    tags-ignore:
      - '*.*.*'
    paths-ignore:
      - 'README.md'
      - 'docs/**'
  pull_request:
    branches:
      - 'main'
    paths-ignore:
      - 'README.md'
      - 'docs/**'

defaults:
  run:
    working-directory: backend

permissions:
  checks: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build --debug
          build-root-directory: backend
      - name: Publish test report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Escape Camp test report
          path: build/test-results/**/*.xml
          reporter: java-junit
          working-directory: backend
